let money = 100000;
let income = 10000;
let addExpenses = 'Internet, Taxi';
let deposit = false;
let mission = 1000000;
let period = 9;
console.log(typeof(money));
console.log(typeof(income));
console.log(typeof(deposit));
console.log(addExpenses.length);
console.log('Период равен' + ' ' + period + ' ' + 'месяцев');
console.log('Цель заработать' + ' ' + mission + ' ' + 'долларов');
console.log(addExpenses.toLowerCase());
console.log(addExpenses.split(', '));
let budgetDay = 50;
console.log('budgetDay: ', budgetDay);